# Site settings
title: Christopher Hallahan - User Experience and Web Design Consultant
email: chris@chrishallahan.com
description: "Providing user experience and web design consulting services in Kent, OH."
baseurl: "/portfolio/" # the subpath of your site, e.g. /blog/
url: "http://challahan.github.io" # the base hostname & protocol for your site
twitter_username: challahan
github_username:  challahan

# Build settings
markdown: kramdown

# Collections

collections:
   projects:
     output: true