# Site settings
title: User Experience (UX) and Web Design Consulting in Kent OH
email: chris@chrishallahan.com
description: "Freelancer providing user experience and web design (Drupal/WordPress) consulting services in Kent, Ohio."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.chrishallahan.com" # the base hostname & protocol for your site
twitter_username: challahan
github_username:  challahan

# Build settings
markdown: kramdown

future: true

# Collections

collections:
   projects:
     output: true
